//
// Created by paul on 4/11/21.
//

#ifndef MUNGEM3U_LANGUAGES_H
#define MUNGEM3U_LANGUAGES_H

//
// Created by paul on 4/11/21.
//
/// FixMe: add the national language for many more countries

#include "affiliate.h"
#include "country.h"

typedef enum
{
    kLanguageUnset = 0,
    kLanguageUnknown,
    kLanguageVarious,
    kLanguageAlbanian,
    kLanguageArabic,
    kLanguageAzerbaijan,
    kLanguageBengali,
    kLanguageCatalan,
    kLanguageChinese,
    kLanguageDanish,
    kLanguageDutch,
    kLanguageEnglish,
    kLanguageFinnish,
    kLanguageFrench,
    kLanguageGerman,
    kLanguageGreek,
    kLanguageHindi,
    kLanguageHungarian,
    kLanguageItalian,
    kLanguageJapanese,
    kLanguagePashto,
    kLanguagePolish,
    kLanguagePortuguese,
    kLanguageRussian,
    kLanguageSpanish,
    kLanguageSwedish,
    kLanguageSwiss,
    kLanguageTurkish,
    kLanguageMax
} tLanguage;

const char * lookupLanguageAsString[] =
{
    [kLanguageUnset]      = "Not set",
    [kLanguageUnknown]    = "Unknown",
    [kLanguageVarious]    = "Various",
    [kLanguageArabic]     = "Arabic",
    [kLanguageAlbanian]   = "Albanian",
    [kLanguageAzerbaijan] = "Azerbaijan",
    [kLanguageBengali]    = "Bengali",
    [kLanguageCatalan]    = "Catalon",
    [kLanguageChinese]    = "Chinese",
    [kLanguageDanish]     = "Danish",
    [kLanguageDutch]      = "Dutch",
    [kLanguageEnglish]    = "English",
    [kLanguageFinnish]    = "Finnish",
    [kLanguageFrench]     = "French",
    [kLanguageGerman]     = "German",
    [kLanguageGreek]      = "Greek",
    [kLanguageHindi]      = "Hindi",
    [kLanguageHungarian]  = "Hungarian",
    [kLanguageItalian]    = "Italian",
    [kLanguageJapanese]   = "Japanese",
    [kLanguagePashto]     = "Pashto",
    [kLanguagePolish]     = "Polish",
    [kLanguagePortuguese] = "Portuguese",
    [kLanguageRussian]    = "Russian",
    [kLanguageSpanish]    = "Spanish",
    [kLanguageSwedish]    = "Swedish",
    [kLanguageSwiss]      = "Swiss",
    [kLanguageTurkish]    = "Turkish"
};


tLanguage countryToLanguage[]   =
{
    [ kCountryUnset ]          = kLanguageUnset,
    [ kCountryArmenia ]        = kLanguageUnknown,
    [ kCountryAfghanistan ]    = kLanguagePashto,
    [ kCountryAfrica ]         = kLanguageAlbanian,
    [ kCountryAlbania ]        = kLanguageUnknown,
    [ kCountryAlgeria ]        = kLanguageArabic,
    [ kCountryAmericanSamoa ]  = kLanguageEnglish,
    [ kCountryAndorra ]        = kLanguageCatalan,
    [ kCountryAngola ]         = kLanguagePortuguese,
    [ kCountryAnguilla ]       = kLanguageEnglish,
    [ kCountryArab ]           = kLanguageArabic,
    [ kCountryArgentina ]      = kLanguageSpanish,
    [ kCountryAruba ]          = kLanguageDutch,
    [ kCountryAustralia ]      = kLanguageEnglish,
    [ kCountryAustria ]        = kLanguageHungarian,
    [ kCountryAzerbaijan ]     = kLanguageAzerbaijan,
    [ kCountryBahamas ]        = kLanguageEnglish,
    [ kCountryBahrain ]        = kLanguageArabic,
    [ kCountryBangladesh ]     = kLanguageBengali,
    [ kCountryBarbados ]       = kLanguageEnglish,
    [ kCountryBelarus ]        = kLanguageUnknown,
    [ kCountryBelgium ]        = kLanguageUnknown,
    [ kCountryBelize ]         = kLanguageUnknown,
    [ kCountryBenin ]          = kLanguageUnknown,
    [ kCountryBermuda ]        = kLanguageUnknown,
    [ kCountryBhutan ]         = kLanguageUnknown,
    [ kCountryBolivia ]        = kLanguageUnknown,
    [ kCountryBosnia ]         = kLanguageUnknown,
    [ kCountryBotswana ]       = kLanguageUnknown,
    [ kCountryBrazil ]         = kLanguagePortuguese,
    [ kCountryBrunei ]         = kLanguageUnknown,
    [ kCountryBulgaria ]       = kLanguageUnknown,
    [ kCountryBurundi ]        = kLanguageUnknown,
    [ kCountryCambodia ]       = kLanguageUnknown,
    [ kCountryCameroon ]       = kLanguageUnknown,
    [ kCountryCanada ]         = kLanguageEnglish,
    [ kCountryCaribbean ]      = kLanguageUnknown,
    [ kCountryChad ]           = kLanguageUnknown,
    [ kCountryChile ]          = kLanguageUnknown,
    [ kCountryChina ]          = kLanguageChinese,
    [ kCountryColombia ]       = kLanguageUnknown,
    [ kCountryComoros ]        = kLanguageUnknown,
    [ kCountryCongo ]          = kLanguageUnknown,
    [ kCountryCostaRica ]      = kLanguageUnknown,
    [ kCountryCroatia ]        = kLanguageUnknown,
    [ kCountryCuba ]           = kLanguageUnknown,
    [ kCountryCyprus ]         = kLanguageUnknown,
    [ kCountryCzech ]          = kLanguageUnknown,
    [ kCountryDenmark ]        = kLanguageDanish,
    [ kCountryDominica ]       = kLanguageUnknown,
    [ kCountryDominican ]      = kLanguageUnknown,
    [ kCountryEcuador ]        = kLanguageUnknown,
    [ kCountryEgypt ]          = kLanguageUnknown,
    [ kCountryElSalvador ]     = kLanguageUnknown,
    [ kCountryEstonia ]        = kLanguageUnknown,
    [ kCountryEthiopia ]       = kLanguageUnknown,
    [ kCountryFiji ]           = kLanguageUnknown,
    [ kCountryFinland ]        = kLanguageFinnish,
    [ kCountryFrance ]         = kLanguageFrench,
    [ kCountryGabon ]          = kLanguageUnknown,
    [ kCountryGambia ]         = kLanguageUnknown,
    [ kCountryGeorgia ]        = kLanguageUnknown,
    [ kCountryGermany ]        = kLanguageGerman,
    [ kCountryGhana ]          = kLanguageUnknown,
    [ kCountryGibraltar ]      = kLanguageUnknown,
    [ kCountryGreece ]         = kLanguageUnknown,
    [ kCountryGreenland ]      = kLanguageUnknown,
    [ kCountryGrenada ]        = kLanguageUnknown,
    [ kCountryGuadeloupe ]     = kLanguageUnknown,
    [ kCountryGuam ]           = kLanguageUnknown,
    [ kCountryGuatemala ]      = kLanguageUnknown,
    [ kCountryGuernsey ]       = kLanguageUnknown,
    [ kCountryGuinea ]         = kLanguageUnknown,
    [ kCountryGuyana ]         = kLanguageUnknown,
    [ kCountryHaiti ]          = kLanguageUnknown,
    [ kCountryHonduras ]       = kLanguageUnknown,
    [ kCountryHongKong ]       = kLanguageUnknown,
    [ kCountryHungary ]        = kLanguageUnknown,
    [ kCountryIceland ]        = kLanguageUnknown,
    [ kCountryIndia ]          = kLanguageHindi,
    [ kCountryIndonesia ]      = kLanguageUnknown,
    [ kCountryIran ]           = kLanguageUnknown,
    [ kCountryIraq ]           = kLanguageUnknown,
    [ kCountryIreland ]        = kLanguageEnglish,
    [ kCountryIsrael ]         = kLanguageUnknown,
    [ kCountryItaly ]          = kLanguageItalian,
    [ kCountryJamaica ]        = kLanguageUnknown,
    [ kCountryJapan ]          = kLanguageUnknown,
    [ kCountryJersey ]         = kLanguageEnglish,
    [ kCountryJordan ]         = kLanguageUnknown,
    [ kCountryKazakhstan ]     = kLanguageUnknown,
    [ kCountryKenya ]          = kLanguageUnknown,
    [ kCountryKiribati ]       = kLanguageUnknown,
    [ kCountryKorea ]          = kLanguageUnknown,
    [ kCountryKuwait ]         = kLanguageUnknown,
    [ kCountryKyrgyzstan ]     = kLanguageUnknown,
    [ kCountryLatvia ]         = kLanguageUnknown,
    [ kCountryLebanon ]        = kLanguageUnknown,
    [ kCountryLesotho ]        = kLanguageUnknown,
    [ kCountryLiberia ]        = kLanguageUnknown,
    [ kCountryLibya ]          = kLanguageUnknown,
    [ kCountryLiechtenstein ]  = kLanguageUnknown,
    [ kCountryLithuania ]      = kLanguageUnknown,
    [ kCountryLuxembourg ]     = kLanguageUnknown,
    [ kCountryMacao ]          = kLanguageUnknown,
    [ kCountryMacedonia ]      = kLanguageUnknown,
    [ kCountryMadagascar ]     = kLanguageUnknown,
    [ kCountryMalawi ]         = kLanguageUnknown,
    [ kCountryMalaysia ]       = kLanguageUnknown,
    [ kCountryMaldives ]       = kLanguageUnknown,
    [ kCountryMali ]           = kLanguageUnknown,
    [ kCountryMalta ]          = kLanguageUnknown,
    [ kCountryMartinique ]     = kLanguageUnknown,
    [ kCountryMauritania ]     = kLanguageUnknown,
    [ kCountryMauritius ]      = kLanguageUnknown,
    [ kCountryMayotte ]        = kLanguageUnknown,
    [ kCountryMexico ]         = kLanguageSpanish,
    [ kCountryMicronesia ]     = kLanguageUnknown,
    [ kCountryMoldova ]        = kLanguageUnknown,
    [ kCountryMonaco ]         = kLanguageUnknown,
    [ kCountryMongolia ]       = kLanguageUnknown,
    [ kCountryMontenegro ]     = kLanguageUnknown,
    [ kCountryMontserrat ]     = kLanguageUnknown,
    [ kCountryMorocco ]        = kLanguageUnknown,
    [ kCountryMozambique ]     = kLanguageUnknown,
    [ kCountryMyanmar ]        = kLanguageUnknown,
    [ kCountryNamibia ]        = kLanguageUnknown,
    [ kCountryNauru ]          = kLanguageUnknown,
    [ kCountryNepal ]          = kLanguageUnknown,
    [ kCountryNetherlands ]    = kLanguageDutch,
    [ kCountryNewCaledonia ]   = kLanguageUnknown,
    [ kCountryNewZealand ]     = kLanguageEnglish,
    [ kCountryNicaragua ]      = kLanguageUnknown,
    [ kCountryNiger ]          = kLanguageUnknown,
    [ kCountryNigeria ]        = kLanguageUnknown,
    [ kCountryNorway ]         = kLanguageUnknown,
    [ kCountryOman ]           = kLanguageUnknown,
    [ kCountryPakistan ]       = kLanguageUnknown,
    [ kCountryPalau ]          = kLanguageUnknown,
    [ kCountryPalestine ]      = kLanguageUnknown,
    [ kCountryPanama ]         = kLanguageUnknown,
    [ kCountryPapuaNewGuinea ] = kLanguageUnknown,
    [ kCountryParaguay ]       = kLanguageUnknown,
    [ kCountryPeru ]           = kLanguageUnknown,
    [ kCountryPhilippines ]    = kLanguageUnknown,
    [ kCountryPoland ]         = kLanguagePolish,
    [ kCountryPortugal ]       = kLanguagePortuguese,
    [ kCountryPuertoRico ]     = kLanguageUnknown,
    [ kCountryQatar ]          = kLanguageUnknown,
    [ kCountryRomania ]        = kLanguageUnknown,
    [ kCountryRussia ]         = kLanguageRussian,
    [ kCountryRwanda ]         = kLanguageUnknown,
    [ kCountrySamoa ]          = kLanguageUnknown,
    [ kCountrySanMarino ]      = kLanguageUnknown,
    [ kCountrySaudiArabia ]    = kLanguageArabic,
    [ kCountrySenegal ]        = kLanguageUnknown,
    [ kCountrySerbia ]         = kLanguageUnknown,
    [ kCountrySeychelles ]     = kLanguageUnknown,
    [ kCountrySingapore ]      = kLanguageUnknown,
    [ kCountrySlovakia ]       = kLanguageUnknown,
    [ kCountrySlovenia ]       = kLanguageUnknown,
    [ kCountrySomalia ]        = kLanguageUnknown,
    [ kCountrySouthAfrica ]    = kLanguageUnknown,
    [ kCountrySouthKorea ]     = kLanguageUnknown,
    [ kCountrySpain ]          = kLanguageSpanish,
    [ kCountrySriLanka ]       = kLanguageUnknown,
    [ kCountrySuriname ]       = kLanguageUnknown,
    [ kCountrySwaziland ]      = kLanguageUnknown,
    [ kCountrySweden ]         = kLanguageSwedish,
    [ kCountrySwitzerland ]    = kLanguageSwiss,
    [ kCountrySyria ]          = kLanguageUnknown,
    [ kCountryTaiwan ]         = kLanguageUnknown,
    [ kCountryTajikistan ]     = kLanguageUnknown,
    [ kCountryTanzania ]       = kLanguageUnknown,
    [ kCountryThailand ]       = kLanguageUnknown,
    [ kCountryTogo ]           = kLanguageUnknown,
    [ kCountryTokelau ]        = kLanguageUnknown,
    [ kCountryTonga ]          = kLanguageUnknown,
    [ kCountryTunisia ]        = kLanguageUnknown,
    [ kCountryTurkey ]         = kLanguageUnknown,
    [ kCountryTurkmenistan ]   = kLanguageUnknown,
    [ kCountryUAE ]            = kLanguageArabic,
    [ kCountryUganda ]         = kLanguageUnknown,
    [ kCountryUkraine ]        = kLanguageUnknown,
    [ kCountryUnitedKingdom ]  = kLanguageEnglish,
    [ kCountryUnitedStates ]   = kLanguageEnglish,
    [ kCountryUruguay ]        = kLanguageUnknown,
    [ kCountryUzbekistan ]     = kLanguageUnknown,
    [ kCountryVenezuela ]      = kLanguageUnknown,
    [ kCountryVietnam ]        = kLanguageUnknown,
    [ kCountryYemen ]          = kLanguageUnknown,
    [ kCountryZambia ]         = kLanguageUnknown,
    [ kCountryZimbabwe ]       = kLanguageUnknown
};

tLanguage affiliateToLanguage[] =
    {
        [kAffiliateUnset]     = kLanguageUnset,
        [kAffiliateABC]       = kLanguageEnglish,   /* American or Australian Broadcasting Company */
        [kAffiliateBBC]       = kLanguageEnglish,   /* UK - British Broadcasting Company */
        [kAffiliateCBC]       = kLanguageEnglish,   /* Canada */
        [kAffiliateCBS]       = kLanguageEnglish,   /* US */
        [kAffiliateCITY]      = kLanguageEnglish,
        [kAffiliateCTV]       = kLanguageEnglish,
        [kAffiliateCW]        = kLanguageEnglish,   /* US */
        [kAffiliateDaystar]   = kLanguageEnglish,
        [kAffiliateETV]       = kLanguageUnknown,
        [kAffiliateFox]       = kLanguageEnglish,   /* US */
        [kAffiliateITV]       = kLanguageEnglish,   /* UK - Independent Television */
        [kAffiliateInd]       = kLanguageUnknown,
        [kAffiliateIon]       = kLanguageEnglish,
        [kAffiliateMyTV]      = kLanguageEnglish,
        [kAffiliateNBC]       = kLanguageEnglish,   /* US */
        [kAffiliatePBS]       = kLanguageEnglish,   /* US - Public Broadcasting Service */
        [kAffiliateRogers]    = kLanguageEnglish,
        [kAffiliateSTV]       = kLanguageEnglish,   /* */
        [kAffiliateSky]       = kLanguageEnglish,
        [kAffiliateTelemundo] = kLanguageSpanish,   /* Spanish Language US Network */
        [kAffiliateTrinity]   = kLanguageEnglish,
        [kAffiliateUniMas]    = kLanguageSpanish,   /* Spanish Language US Network */
        [kAffiliateUnivision] = kLanguageSpanish    /* Spanish Language US Network */
    };

typedef enum {
    kRegionUnset = 0,
    kRegionOther,
    kRegionAfrica,
    kRegionAsia,
    kRegionAustralia,
    kRegionChina,
    kRegionEasternEurope,
    kRegionEurope,
    kRegionMiddleEast,
    kRegionRussia,
    kRegionNorthAmerica,
    kRegionSouthAmerica
} tRegionIndex;


const char * lookupRegionAsString[] =
{
    [ kRegionUnset ]         = "Not set",
    [ kRegionOther ]         = "Other",
    [ kRegionAfrica ]        = "Africa",
    [ kRegionAsia ]          = "Asia",
    [ kRegionAustralia ]     = "Australia",
    [ kRegionChina ]         = "China",
    [ kRegionEasternEurope ] = "Eastern Europe",
    [ kRegionEurope ]        = "Europe",
    [ kRegionMiddleEast ]    = "Middle East",
    [ kRegionRussia ]        = "Russia",
    [ kRegionNorthAmerica ]  = "North America",
    [ kRegionSouthAmerica ]  = "South America"
};


tRegionIndex countryToRegion[] =
{
    [ kCountryUnset ]          = kRegionUnset,
    [ kCountryArmenia ]        = kRegionAsia,
    [ kCountryAfghanistan ]    = kRegionAsia,
    [ kCountryAfrica ]         = kRegionAfrica,
    [ kCountryAlbania ]        = kRegionOther,
    [ kCountryAlgeria ]        = kRegionOther,
    [ kCountryAmericanSamoa ]  = kRegionOther,
    [ kCountryAndorra ]        = kRegionOther,
    [ kCountryAngola ]         = kRegionOther,
    [ kCountryAnguilla ]       = kRegionOther,
    [ kCountryArab ]           = kRegionOther,
    [ kCountryArgentina ]      = kRegionSouthAmerica,
    [ kCountryAruba ]          = kRegionOther,
    [ kCountryAustralia ]      = kRegionAustralia,
    [ kCountryAustria ]        = kRegionOther,
    [ kCountryAzerbaijan ]     = kRegionOther,
    [ kCountryBahamas ]        = kRegionOther,
    [ kCountryBahrain ]        = kRegionOther,
    [ kCountryBangladesh ]     = kRegionOther,
    [ kCountryBarbados ]       = kRegionOther,
    [ kCountryBelarus ]        = kRegionOther,
    [ kCountryBelgium ]        = kRegionEurope,
    [ kCountryBelize ]         = kRegionOther,
    [ kCountryBenin ]          = kRegionOther,
    [ kCountryBermuda ]        = kRegionOther,
    [ kCountryBhutan ]         = kRegionOther,
    [ kCountryBolivia ]        = kRegionOther,
    [ kCountryBosnia ]         = kRegionEasternEurope,
    [ kCountryBotswana ]       = kRegionAfrica,
    [ kCountryBrazil ]         = kRegionSouthAmerica,
    [ kCountryBrunei ]         = kRegionOther,
    [ kCountryBulgaria ]       = kRegionEasternEurope,
    [ kCountryBurundi ]        = kRegionOther,
    [ kCountryCambodia ]       = kRegionOther,
    [ kCountryCameroon ]       = kRegionOther,
    [ kCountryCanada ]         = kRegionNorthAmerica,
    [ kCountryCaribbean ]      = kRegionOther,
    [ kCountryChad ]           = kRegionOther,
    [ kCountryChile ]          = kRegionSouthAmerica,
    [ kCountryChina ]          = kRegionChina,
    [ kCountryColombia ]       = kRegionOther,
    [ kCountryComoros ]        = kRegionOther,
    [ kCountryCongo ]          = kRegionOther,
    [ kCountryCostaRica ]      = kRegionOther,
    [ kCountryCroatia ]        = kRegionOther,
    [ kCountryCuba ]           = kRegionOther,
    [ kCountryCyprus ]         = kRegionOther,
    [ kCountryCzech ]          = kRegionEasternEurope,
    [ kCountryDenmark ]        = kRegionEurope,
    [ kCountryDominica ]       = kRegionOther,
    [ kCountryDominican ]      = kRegionOther,
    [ kCountryEcuador ]        = kRegionOther,
    [ kCountryEgypt ]          = kRegionMiddleEast,
    [ kCountryElSalvador ]     = kRegionOther,
    [ kCountryEstonia ]        = kRegionOther,
    [ kCountryEthiopia ]       = kRegionAfrica,
    [ kCountryFiji ]           = kRegionOther,
    [ kCountryFinland ]        = kRegionEurope,
    [ kCountryFrance ]         = kRegionEurope,
    [ kCountryGabon ]          = kRegionOther,
    [ kCountryGambia ]         = kRegionOther,
    [ kCountryGeorgia ]        = kRegionOther,
    [ kCountryGermany ]        = kRegionEurope,
    [ kCountryGhana ]          = kRegionOther,
    [ kCountryGibraltar ]      = kRegionEurope,
    [ kCountryGreece ]         = kRegionEurope,
    [ kCountryGreenland ]      = kRegionOther,
    [ kCountryGrenada ]        = kRegionOther,
    [ kCountryGuadeloupe ]     = kRegionOther,
    [ kCountryGuam ]           = kRegionOther,
    [ kCountryGuatemala ]      = kRegionOther,
    [ kCountryGuernsey ]       = kRegionOther,
    [ kCountryGuinea ]         = kRegionOther,
    [ kCountryGuyana ]         = kRegionOther,
    [ kCountryHaiti ]          = kRegionOther,
    [ kCountryHonduras ]       = kRegionSouthAmerica,
    [ kCountryHongKong ]       = kRegionChina,
    [ kCountryHungary ]        = kRegionEasternEurope,
    [ kCountryIceland ]        = kRegionOther,
    [ kCountryIndia ]          = kRegionAsia,
    [ kCountryIndonesia ]      = kRegionOther,
    [ kCountryIran ]           = kRegionMiddleEast,
    [ kCountryIraq ]           = kRegionMiddleEast,
    [ kCountryIreland ]        = kRegionOther,
    [ kCountryIsrael ]         = kRegionMiddleEast,
    [ kCountryItaly ]          = kRegionEurope,
    [ kCountryJamaica ]        = kRegionOther,
    [ kCountryJapan ]          = kRegionAsia,
    [ kCountryJersey ]         = kRegionOther,
    [ kCountryJordan ]         = kRegionOther,
    [ kCountryKazakhstan ]     = kRegionOther,
    [ kCountryKenya ]          = kRegionOther,
    [ kCountryKiribati ]       = kRegionOther,
    [ kCountryKorea ]          = kRegionAsia,
    [ kCountryKuwait ]         = kRegionMiddleEast,
    [ kCountryKyrgyzstan ]     = kRegionOther,
    [ kCountryLatvia ]         = kRegionOther,
    [ kCountryLebanon ]        = kRegionMiddleEast,
    [ kCountryLesotho ]        = kRegionOther,
    [ kCountryLiberia ]        = kRegionOther,
    [ kCountryLibya ]          = kRegionMiddleEast,
    [ kCountryLiechtenstein ]  = kRegionOther,
    [ kCountryLithuania ]      = kRegionOther,
    [ kCountryLuxembourg ]     = kRegionEurope,
    [ kCountryMacao ]          = kRegionOther,
    [ kCountryMacedonia ]      = kRegionOther,
    [ kCountryMadagascar ]     = kRegionOther,
    [ kCountryMalawi ]         = kRegionOther,
    [ kCountryMalaysia ]       = kRegionAsia,
    [ kCountryMaldives ]       = kRegionOther,
    [ kCountryMali ]           = kRegionOther,
    [ kCountryMalta ]          = kRegionOther,
    [ kCountryMartinique ]     = kRegionOther,
    [ kCountryMauritania ]     = kRegionOther,
    [ kCountryMauritius ]      = kRegionOther,
    [ kCountryMayotte ]        = kRegionOther,
    [ kCountryMexico ]         = kRegionSouthAmerica,
    [ kCountryMicronesia ]     = kRegionOther,
    [ kCountryMoldova ]        = kRegionOther,
    [ kCountryMonaco ]         = kRegionEurope,
    [ kCountryMongolia ]       = kRegionChina,
    [ kCountryMontenegro ]     = kRegionOther,
    [ kCountryMontserrat ]     = kRegionOther,
    [ kCountryMorocco ]        = kRegionOther,
    [ kCountryMozambique ]     = kRegionOther,
    [ kCountryMyanmar ]        = kRegionOther,
    [ kCountryNamibia ]        = kRegionOther,
    [ kCountryNauru ]          = kRegionOther,
    [ kCountryNepal ]          = kRegionOther,
    [ kCountryNetherlands ]    = kRegionEurope,
    [ kCountryNewCaledonia ]   = kRegionOther,
    [ kCountryNewZealand ]     = kRegionAustralia,
    [ kCountryNicaragua ]      = kRegionOther,
    [ kCountryNiger ]          = kRegionOther,
    [ kCountryNigeria ]        = kRegionOther,
    [ kCountryNorway ]         = kRegionOther,
    [ kCountryOman ]           = kRegionOther,
    [ kCountryPakistan ]       = kRegionAsia,
    [ kCountryPalau ]          = kRegionOther,
    [ kCountryPalestine ]      = kRegionMiddleEast,
    [ kCountryPanama ]         = kRegionSouthAmerica,
    [ kCountryPapuaNewGuinea ] = kRegionOther,
    [ kCountryParaguay ]       = kRegionOther,
    [ kCountryPeru ]           = kRegionOther,
    [ kCountryPhilippines ]    = kRegionOther,
    [ kCountryPoland ]         = kRegionOther,
    [ kCountryPortugal ]       = kRegionEurope,
    [ kCountryPuertoRico ]     = kRegionOther,
    [ kCountryQatar ]          = kRegionOther,
    [ kCountryRomania ]        = kRegionEasternEurope,
    [ kCountryRussia ]         = kRegionRussia,
    [ kCountryRwanda ]         = kRegionOther,
    [ kCountrySamoa ]          = kRegionOther,
    [ kCountrySanMarino ]      = kRegionOther,
    [ kCountrySaudiArabia ]    = kRegionMiddleEast,
    [ kCountrySenegal ]        = kRegionOther,
    [ kCountrySerbia ]         = kRegionOther,
    [ kCountrySeychelles ]     = kRegionOther,
    [ kCountrySingapore ]      = kRegionOther,
    [ kCountrySlovakia ]       = kRegionOther,
    [ kCountrySlovenia ]       = kRegionOther,
    [ kCountrySomalia ]        = kRegionOther,
    [ kCountrySouthAfrica ]    = kRegionOther,
    [ kCountrySouthKorea ]     = kRegionOther,
    [ kCountrySpain ]          = kRegionOther,
    [ kCountrySriLanka ]       = kRegionOther,
    [ kCountrySuriname ]       = kRegionOther,
    [ kCountrySwaziland ]      = kRegionOther,
    [ kCountrySweden ]         = kRegionEurope,
    [ kCountrySwitzerland ]    = kRegionOther,
    [ kCountrySyria ]          = kRegionOther,
    [ kCountryTaiwan ]         = kRegionOther,
    [ kCountryTajikistan ]     = kRegionOther,
    [ kCountryTanzania ]       = kRegionOther,
    [ kCountryThailand ]       = kRegionAsia,
    [ kCountryTogo ]           = kRegionOther,
    [ kCountryTokelau ]        = kRegionOther,
    [ kCountryTonga ]          = kRegionOther,
    [ kCountryTunisia ]        = kRegionOther,
    [ kCountryTurkey ]         = kRegionEurope,
    [ kCountryTurkmenistan ]   = kRegionOther,
    [ kCountryUAE ]            = kRegionMiddleEast,
    [ kCountryUganda ]         = kRegionOther,
    [ kCountryUkraine ]        = kRegionEasternEurope,
    [ kCountryUnitedKingdom ]  = kRegionEurope,
    [ kCountryUnitedStates ]   = kRegionNorthAmerica,
    [ kCountryUruguay ]        = kRegionOther,
    [ kCountryUzbekistan ]     = kRegionOther,
    [ kCountryVenezuela ]      = kRegionOther,
    [ kCountryVietnam ]        = kRegionAsia,
    [ kCountryYemen ]          = kRegionOther,
    [ kCountryZambia ]         = kRegionAfrica,
    [ kCountryZimbabwe ]       = kRegionAfrica
};

#endif //MUNGEM3U_LANGUAGES_H
