//
// Created by paul on 4/11/21.
//

#ifndef MUNGEM3U_LANGUAGES_H
#define MUNGEM3U_LANGUAGES_H

//
// Created by paul on 4/11/21.
//
/// FixMe: add the national language for many more countries

#include "affiliate.h"
#include "country.h"

typedef enum
{
    kLanguageUnknown = 0,
    kLanguageArabic,
    kLanguageChinese,
    kLanguageDutch,
    kLanguageEnglish,
    kLanguageFrench,
    kLanguageGerman,
    kLanguageGreek,
    kLanguageJapanese,
    kLanguagePolish,
    kLanguagePortuguese,
    kLanguageSpanish,
    kLanguageSwedish,
    kLanguageTurkish,
    kLanguageMax
} tLanguage;

const char * lookupLanguageAsString[] =
                   {
                           [kLanguageUnknown]    = "Unknown",
                           [kLanguageArabic]     = "Arabic",
                           [kLanguageChinese]    = "Chinese",
                           [kLanguageDutch]      = "Dutch",
                           [kLanguageEnglish]    = "English",
                           [kLanguageFrench]     = "French",
                           [kLanguageGerman]     = "German",
                           [kLanguageGreek]      = "Greek",
                           [kLanguageJapanese]   = "Japanese",
                           [kLanguagePolish]     = "Polish",
                           [kLanguagePortuguese] = "Portuguese",
                           [kLanguageSpanish]    = "Spanish",
                           [kLanguageSwedish]    = "Swedish",
                           [kLanguageTurkish]    = "Turkish"
                   };

tLanguage countryToLanguage[]   =
                  {
                          [kCountryUnknown]           = kLanguageUnknown,

                          [kCountryAF        ] = kLanguageUnknown,
                          [kCountryAfrica    ] = kLanguageUnknown,
                          [kCountryAL        ] = kLanguageUnknown,
                          [kCountryDZ        ] = kLanguageUnknown,
                          [kCountryAS        ] = kLanguageUnknown,
                          [kCountryAD        ] = kLanguageUnknown,
                          [kCountryAO        ] = kLanguageUnknown,
                          [kCountryAI        ] = kLanguageUnknown,
                          [kCountryAR        ] = kLanguageArabic,
                          [kCountryArgentina ] = kLanguageUnknown,
                          [kCountryAM        ] = kLanguageUnknown,
                          [kCountryAW        ] = kLanguageUnknown,
                          [kCountryAU        ] = kLanguageEnglish,
                          [kCountryAT        ] = kLanguageUnknown,
                          [kCountryAZ        ] = kLanguageUnknown,
                          [kCountryBS        ] = kLanguageUnknown,
                          [kCountryBH        ] = kLanguageUnknown,
                          [kCountryBD        ] = kLanguageUnknown,
                          [kCountryBB        ] = kLanguageUnknown,
                          [kCountryBY        ] = kLanguageUnknown,
                          [kCountryBE        ] = kLanguageUnknown,
                          [kCountryBZ        ] = kLanguageUnknown,
                          [kCountryBJ        ] = kLanguageUnknown,
                          [kCountryBM        ] = kLanguageUnknown,
                          [kCountryBT        ] = kLanguageUnknown,
                          [kCountryBO        ] = kLanguageUnknown,
                          [kCountryBA        ] = kLanguageUnknown,
                          [kCountryBW        ] = kLanguageUnknown,
                          [kCountryBR        ] = kLanguagePortuguese,
                          [kCountryBN        ] = kLanguageUnknown,
                          [kCountryBG        ] = kLanguageUnknown,
                          [kCountryBI        ] = kLanguageUnknown,
                          [kCountryKH        ] = kLanguageUnknown,
                          [kCountryCM        ] = kLanguageUnknown,
                          [kCountryCA        ] = kLanguageEnglish,
                          [kCountryCaribbean ] = kLanguageUnknown,
                          [kCountryTD        ] = kLanguageUnknown,
                          [kCountryCL        ] = kLanguageUnknown,
                          [kCountryCN        ] = kLanguageChinese,
                          [kCountryCO        ] = kLanguageUnknown,
                          [kCountryKM        ] = kLanguageUnknown,
                          [kCountryCD        ] = kLanguageUnknown,
                          [kCountryCR        ] = kLanguageUnknown,
                          [kCountryHR        ] = kLanguageUnknown,
                          [kCountryCU        ] = kLanguageUnknown,
                          [kCountryCY        ] = kLanguageUnknown,
                          [kCountryCZ        ] = kLanguageUnknown,
                          [kCountryDK        ] = kLanguageUnknown,
                          [kCountryDM        ] = kLanguageUnknown,
                          [kCountryDO        ] = kLanguageUnknown,
                          [kCountryEC        ] = kLanguageUnknown,
                          [kCountryEG        ] = kLanguageUnknown,
                          [kCountrySV        ] = kLanguageUnknown,
                          [kCountryEE        ] = kLanguageUnknown,
                          [kCountryET        ] = kLanguageUnknown,
                          [kCountryFJ        ] = kLanguageUnknown,
                          [kCountryFI        ] = kLanguageUnknown,
                          [kCountryFR        ] = kLanguageFrench,
                          [kCountryGA        ] = kLanguageUnknown,
                          [kCountryGM        ] = kLanguageUnknown,
                          [kCountryGE        ] = kLanguageUnknown,
                          [kCountryDE        ] = kLanguageGerman,
                          [kCountryGH        ] = kLanguageUnknown,
                          [kCountryGI        ] = kLanguageUnknown,
                          [kCountryGR        ] = kLanguageGreek,
                          [kCountryGL        ] = kLanguageUnknown,
                          [kCountryGD        ] = kLanguageUnknown,
                          [kCountryGP        ] = kLanguageUnknown,
                          [kCountryGU        ] = kLanguageUnknown,
                          [kCountryGT        ] = kLanguageUnknown,
                          [kCountryGG        ] = kLanguageUnknown,
                          [kCountryGN        ] = kLanguageUnknown,
                          [kCountryGY        ] = kLanguageUnknown,
                          [kCountryHT        ] = kLanguageUnknown,
                          [kCountryHN        ] = kLanguageUnknown,
                          [kCountryHK        ] = kLanguageUnknown,
                          [kCountryHU        ] = kLanguageUnknown,
                          [kCountryIS        ] = kLanguageUnknown,
                          [kCountryIN        ] = kLanguageUnknown,
                          [kCountryID        ] = kLanguageUnknown,
                          [kCountryIR        ] = kLanguageUnknown,
                          [kCountryIQ        ] = kLanguageUnknown,
                          [kCountryIE        ] = kLanguageEnglish,
                          [kCountryIL        ] = kLanguageUnknown,
                          [kCountryIT        ] = kLanguageUnknown,
                          [kCountryJM        ] = kLanguageUnknown,
                          [kCountryJP        ] = kLanguageJapanese,
                          [kCountryJE        ] = kLanguageUnknown,
                          [kCountryJO        ] = kLanguageUnknown,
                          [kCountryKZ        ] = kLanguageUnknown,
                          [kCountryKE        ] = kLanguageUnknown,
                          [kCountryKI        ] = kLanguageUnknown,
                          [kCountryKR        ] = kLanguageUnknown,
                          [kCountryKW        ] = kLanguageUnknown,
                          [kCountryKG        ] = kLanguageUnknown,
                          [kCountryLV        ] = kLanguageUnknown,
                          [kCountryLB        ] = kLanguageUnknown,
                          [kCountryLS        ] = kLanguageUnknown,
                          [kCountryLR        ] = kLanguageUnknown,
                          [kCountryLY        ] = kLanguageUnknown,
                          [kCountryLI        ] = kLanguageUnknown,
                          [kCountryLT        ] = kLanguageUnknown,
                          [kCountryLU        ] = kLanguageUnknown,
                          [kCountryMO        ] = kLanguageUnknown,
                          [kCountryMK        ] = kLanguageUnknown,
                          [kCountryMG        ] = kLanguageUnknown,
                          [kCountryMW        ] = kLanguageUnknown,
                          [kCountryMY        ] = kLanguageUnknown,
                          [kCountryMV        ] = kLanguageUnknown,
                          [kCountryML        ] = kLanguageUnknown,
                          [kCountryMT        ] = kLanguageUnknown,
                          [kCountryMQ        ] = kLanguageUnknown,
                          [kCountryMR        ] = kLanguageUnknown,
                          [kCountryMU        ] = kLanguageUnknown,
                          [kCountryYT        ] = kLanguageUnknown,
                          [kCountryMX        ] = kLanguageUnknown,
                          [kCountryFM        ] = kLanguageUnknown,
                          [kCountryMD        ] = kLanguageUnknown,
                          [kCountryMC        ] = kLanguageUnknown,
                          [kCountryMN        ] = kLanguageUnknown,
                          [kCountryME        ] = kLanguageUnknown,
                          [kCountryMS        ] = kLanguageUnknown,
                          [kCountryMA        ] = kLanguageUnknown,
                          [kCountryMZ        ] = kLanguageUnknown,
                          [kCountryMM        ] = kLanguageUnknown,
                          [kCountryNA        ] = kLanguageUnknown,
                          [kCountryNR        ] = kLanguageUnknown,
                          [kCountryNP        ] = kLanguageUnknown,
                          [kCountryNL        ] = kLanguageDutch,
                          [kCountryNC        ] = kLanguageUnknown,
                          [kCountryNZ        ] = kLanguageEnglish,
                          [kCountryNI        ] = kLanguageUnknown,
                          [kCountryNE        ] = kLanguageUnknown,
                          [kCountryNG        ] = kLanguageUnknown,
                          [kCountryNO        ] = kLanguageUnknown,
                          [kCountryOM        ] = kLanguageUnknown,
                          [kCountryPK        ] = kLanguageUnknown,
                          [kCountryPW        ] = kLanguageUnknown,
                          [kCountryPS        ] = kLanguageUnknown,
                          [kCountryPA        ] = kLanguageUnknown,
                          [kCountryPG        ] = kLanguageUnknown,
                          [kCountryPY        ] = kLanguageUnknown,
                          [kCountryPE        ] = kLanguageUnknown,
                          [kCountryPH        ] = kLanguageUnknown,
                          [kCountryPL        ] = kLanguagePolish,
                          [kCountryPT        ] = kLanguagePortuguese,
                          [kCountryPR        ] = kLanguageUnknown,
                          [kCountryQA        ] = kLanguageUnknown,
                          [kCountryRO        ] = kLanguageUnknown,
                          [kCountryRU        ] = kLanguageUnknown,
                          [kCountryRW        ] = kLanguageUnknown,
                          [kCountryWS        ] = kLanguageUnknown,
                          [kCountrySM        ] = kLanguageUnknown,
                          [kCountrySA        ] = kLanguageUnknown,
                          [kCountrySN        ] = kLanguageUnknown,
                          [kCountryRS        ] = kLanguageUnknown,
                          [kCountrySC        ] = kLanguageUnknown,
                          [kCountrySG        ] = kLanguageUnknown,
                          [kCountrySK        ] = kLanguageUnknown,
                          [kCountrySI        ] = kLanguageUnknown,
                          [kCountrySO        ] = kLanguageUnknown,
                          [kCountryZA        ] = kLanguageUnknown,
                          [kCountryES        ] = kLanguageSpanish,
                          [kCountryLK        ] = kLanguageUnknown,
                          [kCountrySD        ] = kLanguageUnknown,
                          [kCountrySR        ] = kLanguageUnknown,
                          [kCountrySZ        ] = kLanguageUnknown,
                          [kCountrySE        ] = kLanguageSwedish,
                          [kCountryCH        ] = kLanguageUnknown,
                          [kCountrySY        ] = kLanguageUnknown,
                          [kCountryTW        ] = kLanguageUnknown,
                          [kCountryTJ        ] = kLanguageUnknown,
                          [kCountryTZ        ] = kLanguageUnknown,
                          [kCountryTH        ] = kLanguageUnknown,
                          [kCountryTG        ] = kLanguageUnknown,
                          [kCountryTK        ] = kLanguageUnknown,
                          [kCountryTO        ] = kLanguageUnknown,
                          [kCountryTN        ] = kLanguageUnknown,
                          [kCountryTR        ] = kLanguageTurkish,
                          [kCountryTM        ] = kLanguageUnknown,
                          [kCountryUAE       ] = kLanguageArabic,
                          [kCountryUG        ] = kLanguageEnglish,
                          [kCountryUK        ] = kLanguageEnglish,
                          [kCountryUA        ] = kLanguageUnknown,
                          [kCountryUY        ] = kLanguageUnknown,
                          [kCountryUS        ] = kLanguageUnknown,
                          [kCountryUZ        ] = kLanguageUnknown,
                          [kCountryVE        ] = kLanguageUnknown,
                          [kCountryVN        ] = kLanguageUnknown,
                          [kCountryYE        ] = kLanguageUnknown,
                          [kCountryZM        ] = kLanguageUnknown,
                          [kCountryZW        ] = kLanguageUnknown
                  };

tLanguage affiliateToLanguage[] =
                  {
                      [kAffiliateUnknown]   = kLanguageUnknown,
                      [kAffiliateABC]       = kLanguageEnglish,    /* American or Australian */
                      [kAffiliateBBC]       = kLanguageEnglish,
                      [kAffiliateCBC]       = kLanguageEnglish,
                      [kAffiliateCBS]       = kLanguageEnglish,
                      [kAffiliateCTV]       = kLanguageEnglish,
                      [kAffiliateCW]        = kLanguageEnglish,
                      [kAffiliateFox]       = kLanguageEnglish,
                      [kAffiliateITV]       = kLanguageEnglish,
                      [kAffiliateNBC]       = kLanguageEnglish,
                      [kAffiliatePBS]       = kLanguageEnglish,
                      [kAffiliateSTV]       = kLanguageEnglish,
                      [kAffiliateTelemundo] = kLanguageSpanish,
                      [kAffiliateUniMas]    = kLanguageSpanish,
                      [kAffiliateUnivision] = kLanguageSpanish
                  };

#endif //MUNGEM3U_LANGUAGES_H
